name: Build cn_ip_cidr.rsc

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/routeros-cnip-cidr

      - name: Update cn_ip_cidr.rsc
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |-
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android /usr/lib/jvm /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          bash $GITHUB_WORKSPACE/routeros-cnip-cidr/generator.bash

      - name: Commit and push if changed
        run: |-
          cd $GITHUB_WORKSPACE/routeros-cnip-cidr/
          git diff
          git config --global user.email "generator-bot@rookiezoe.com"
          git config --global user.name "generator-bot"
          git add -A
          git commit -m "Update 'cn_ip_cidr.rsc'" || exit 0
          git push
